// Generated by CoffeeScript 1.7.1
(function() {
  var ccjs, path, stripExt;

  path = require('path');

  ccjs = require('ccjs');

  stripExt = function(filename) {
    return filename.substr(0, filename.length - path.extname(filename).length);
  };

  module.exports = function(grunt) {
    return grunt.registerTask('ccjs', 'grunt plugin for ccjs', function() {
      var coffee, compilers, dest, files, process, root, src, _coffee, _ref, _results;
      files = grunt.config.get(['ccjs', 'files']);
      _ref = grunt.config.get(['ccjs', 'options'], {
        root: './'
      }), root = _ref.root, coffee = _ref.coffee;
      compilers = {};
      if (coffee) {
        _coffee = require('coffee-script');
        compilers.coffee = function(js) {
          return _coffee.compile(js, {
            bare: true
          });
        };
      }
      process = function(src, dest) {
        var realpath;
        realpath = stripExt(path.join(root, src));
        grunt.file.write(dest, ccjs.bundle(realpath, root, compilers));
        return grunt.log.writeln("File " + dest + " created.");
      };
      _results = [];
      for (dest in files) {
        src = files[dest];
        _results.push(process(src, dest));
      }
      return _results;
    });
  };

}).call(this);
